export const product = [
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image1.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image2.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image3.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image4.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image5.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image6.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image7.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image8.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image9.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image10.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image11.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image12.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image13.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image14.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image15.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image16.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image17.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image18.jpg'),
  },
  {
    name: 'Baby Dress',
    price: '$20',
    brand: 'The Wolf',
    image: require('./images/image19.jpg'),
  },
];
